import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';import FormData from 'form-data';import {mkdtemp,readFile,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';import type{FastifyInstance}from'fastify';import{buildApp}from'../src/app.js';import{prisma}from'../src/plugins/prisma.js';
const databaseUrl=process.env.TEST_DATABASE_URL;const suite=databaseUrl?describe:describe.skip;let app:FastifyInstance,tmp:string;
function cookie(res:{headers:Record<string,unknown>}){return String(res.headers['set-cookie']).split(';')[0]}
async function register(email:string){const r=await app.inject({method:'POST',url:'/api/auth/register',payload:{email,password:'password123'}});return{response:r,cookie:cookie(r)}}
suite('DepotDrive integration',()=>{beforeAll(async()=>{process.env.DATABASE_URL=databaseUrl;tmp=await mkdtemp(path.join(os.tmpdir(),'depot-test-'));app=await buildApp({logger:false,env:{NODE_ENV:'test',DATABASE_URL:databaseUrl!,JWT_SECRET:'test-secret',API_PORT:3000,WEB_ORIGIN:'http://localhost:5173',COOKIE_SECURE:false,JWT_SESSION_SECONDS:604800,MAX_FILE_SIZE_BYTES:1024,UPLOAD_ROOT:tmp}});await prisma.$connect()});beforeEach(async()=>{await prisma.file.deleteMany();await prisma.folder.deleteMany();await prisma.user.deleteMany()});afterAll(async()=>{await app?.close();await prisma.$disconnect();if(tmp)await rm(tmp,{recursive:true,force:true})});
 it('registers, rejects duplicate email and bad password login',async()=>{const a=await register('USER@example.com');expect(a.response.statusCode).toBe(201);expect(a.response.json().user.email).toBe('user@example.com');expect((await register('user@example.com')).response.statusCode).toBe(409);const bad=await app.inject({method:'POST',url:'/api/auth/login',payload:{email:'user@example.com',password:'wrongpass'}});expect(bad.statusCode).toBe(401)});
 it('rejects unauthenticated file access',async()=>{expect((await app.inject({method:'GET',url:'/api/files/00000000-0000-0000-0000-000000000000/download'})).statusCode).toBe(401)});
 it('creates root/child folders, rejects duplicates and only deletes empty folders',async()=>{const u=await register('folders@example.com');const root=await app.inject({method:'POST',url:'/api/folders',headers:{cookie:u.cookie},payload:{name:'Root',parentId:null}});expect(root.statusCode).toBe(201);expect((await app.inject({method:'POST',url:'/api/folders',headers:{cookie:u.cookie},payload:{name:'Root',parentId:null}})).statusCode).toBe(409);const child=await app.inject({method:'POST',url:'/api/folders',headers:{cookie:u.cookie},payload:{name:'Child',parentId:root.json().id}});expect(child.statusCode).toBe(201);expect((await app.inject({method:'DELETE',url:`/api/folders/${root.json().id}`,headers:{cookie:u.cookie}})).statusCode).toBe(409);expect((await app.inject({method:'DELETE',url:`/api/folders/${child.json().id}`,headers:{cookie:u.cookie}})).statusCode).toBe(204)});
 it('hides another user folders and files with 404',async()=>{const a=await register('a@example.com'),b=await register('b@example.com');const ua=await prisma.user.findUniqueOrThrow({where:{email:'a@example.com'}});const folder=await prisma.folder.create({data:{ownerId:ua.id,name:'Private'}});const file=await prisma.file.create({data:{ownerId:ua.id,name:'x.txt',originalName:'x.txt',mimeType:'text/plain',sizeBytes:1,storageKey:'00000000-0000-4000-8000-000000000001',checksum:'x'}});for(const request of[{method:'GET',url:`/api/folders?parentId=${folder.id}`},{method:'GET',url:`/api/files/${file.id}/download`},{method:'PATCH',url:`/api/files/${file.id}`,payload:{name:'stolen'}},{method:'DELETE',url:`/api/files/${file.id}`}]){const r=await app.inject({...request,headers:{cookie:b.cookie}} as Parameters<typeof app.inject>[0]);expect(r.statusCode).toBe(404)}});
 it('uploads, stores metadata/checksum, downloads, renames metadata and deletes disk+DB',async()=>{const u=await register('file@example.com');const content=Buffer.from('hello depot');const form=new FormData();form.append('folderId','');form.append('file',content,{filename:'hello.txt',contentType:'text/plain'});const uploaded=await app.inject({method:'POST',url:'/api/files/upload',headers:{cookie:u.cookie,...form.getHeaders()},payload:form.getBuffer()});expect(uploaded.statusCode).toBe(201);const dto=uploaded.json();expect(dto.sizeBytes).toBe(content.length);expect(dto.checksum).toBe(createHash('sha256').update(content).digest('hex'));const db=await prisma.file.findUniqueOrThrow({where:{id:dto.id}});expect(await readFile(app.storage.pathFor(db.storageKey))).toEqual(content);const download=await app.inject({method:'GET',url:`/api/files/${dto.id}/download`,headers:{cookie:u.cookie}});expect(download.rawPayload).toEqual(content);await app.inject({method:'PATCH',url:`/api/files/${dto.id}`,headers:{cookie:u.cookie},payload:{name:'renamed.txt'}});const renamed=await prisma.file.findUniqueOrThrow({where:{id:dto.id}});expect(renamed.name).toBe('renamed.txt');expect(renamed.storageKey).toBe(db.storageKey);expect((await app.inject({method:'DELETE',url:`/api/files/${dto.id}`,headers:{cookie:u.cookie}})).statusCode).toBe(204);expect(await prisma.file.findUnique({where:{id:dto.id}})).toBeNull();expect(await app.storage.exists(db.storageKey)).toBe(false)});
 it('rejects files above configured limit',async()=>{const u=await register('large@example.com');const form=new FormData();form.append('folderId','');form.append('file',Buffer.alloc(2048),{filename:'large.bin'});const r=await app.inject({method:'POST',url:'/api/files/upload',headers:{cookie:u.cookie,...form.getHeaders()},payload:form.getBuffer()});expect(r.statusCode).toBe(413)});
});
