import { useRef, useState } from 'react';
import { errorMessage } from '../api';
import { formatBytes } from '../format';
import { listPersistedUploads, startChunkedUpload, uploadActionsForPhase, type ChunkedUploadProgress, type ChunkedUploadTask } from '../chunked-upload';
import { StatusBadge } from './StatusBadge';

type Job={id:string;file:File;progress:ChunkedUploadProgress;error?:string;task?:ChunkedUploadTask};
const initial=(file:File):ChunkedUploadProgress=>({phase:'hashing',loadedBytes:0,totalBytes:file.size,uploadedChunks:0,totalChunks:Math.ceil(file.size/(8*1024*1024)),activeWorkers:0});

export function UploadManager({folderId,onComplete,onNotice}:{folderId:string|null;onComplete:()=>Promise<unknown>;onNotice:(message:string)=>void}){
  const [jobs,setJobs]=useState<Job[]>([]),[persisted,setPersisted]=useState(()=>listPersistedUploads());
  const input=useRef<HTMLInputElement>(null),queue=useRef<Array<{id:string;file:File}>>([]),running=useRef(new Set<string>()),tasks=useRef(new Map<string,ChunkedUploadTask>());

  function update(id:string,patch:(job:Job)=>Job){setJobs(current=>current.map(job=>job.id===id?patch(job):job))}
  function pump(){while(running.current.size<2&&queue.current.length){const next=queue.current.shift()!;run(next.id,next.file)}}
  function run(id:string,file:File){running.current.add(id);update(id,job=>({...job,error:undefined,progress:initial(file)}));const task=startChunkedUpload({file,folderId,onProgress:progress=>{update(id,job=>({...job,progress}));setPersisted(listPersistedUploads())}});tasks.current.set(id,task);update(id,job=>({...job,task}));task.promise.then(async()=>{onNotice(`${file.name} uploaded successfully`);await onComplete()}).catch(error=>{if((error as {name?:string}).name!=='AbortError'&&(error as {name?:string}).name!=='CanceledError')update(id,job=>({...job,error:errorMessage(error,'Upload failed')}))}).finally(()=>{running.current.delete(id);tasks.current.delete(id);setPersisted(listPersistedUploads());pump()})}
  function add(files:FileList|null){if(!files)return;const additions=[...files].map(file=>({id:crypto.randomUUID(),file,progress:initial(file)}));setJobs(current=>[...additions,...current]);queue.current.push(...additions.map(({id,file})=>({id,file})));queueMicrotask(pump)}
  async function cancel(job:Job){queue.current=queue.current.filter(item=>item.id!==job.id);await tasks.current.get(job.id)?.cancel();setJobs(current=>current.filter(item=>item.id!==job.id));setPersisted(listPersistedUploads())}
  function retry(job:Job){if(running.current.has(job.id))return;queue.current.push({id:job.id,file:job.file});pump()}

  return <section className="card mb-6 overflow-hidden" aria-labelledby="upload-manager-title">
    <div className="flex flex-col justify-between gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center"><div><h2 id="upload-manager-title" className="font-bold text-slate-950">Upload manager</h2><p className="mt-1 text-sm text-slate-500">Two files queued at once; each file uses up to four 8 MiB workers.</p></div><button className="btn-primary" data-testid="choose-files" onClick={()=>input.current?.click()}>Choose files</button><input ref={input} data-testid="file-input" className="sr-only" type="file" multiple onChange={event=>{add(event.target.files);event.target.value=''}}/></div>
    {persisted.length>0&&<div className="border-b border-amber-100 bg-amber-50/70 px-5 py-3 text-sm text-amber-900" data-testid="resume-notice"><strong>{persisted.length} unfinished upload{persisted.length>1?'s':''}.</strong> After a refresh, choose the original file again; DepotDrive will query the server and send only missing chunks.</div>}
    {jobs.length===0?<div className="grid place-items-center px-5 py-10 text-center"><div><div className="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-xl">↑</div><p className="mt-3 font-medium">No active uploads</p><p className="mt-1 text-sm text-slate-500">Select one or more files to begin.</p></div></div>:<div className="divide-y divide-slate-100">{jobs.map(job=>{const percent=job.progress.totalBytes?Math.min(100,Math.round(job.progress.loadedBytes/job.progress.totalBytes*100)):job.progress.phase==='complete'?100:0;return <div className="p-5" data-testid={`upload-${job.file.name}`} key={job.id}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-semibold text-slate-900">{job.file.name}</p><StatusBadge status={job.progress.phase}/></div><p className="mt-1 text-xs text-slate-500">{formatBytes(job.file.size)} · {job.progress.uploadedChunks}/{job.progress.totalChunks} chunks · {job.progress.activeWorkers} active worker{job.progress.activeWorkers===1?'':'s'}</p></div><div className="flex gap-2">{uploadActionsForPhase(job.progress.phase).includes('pause')&&<button className="btn-quiet" onClick={()=>tasks.current.get(job.id)?.pause()}>Pause</button>}{uploadActionsForPhase(job.progress.phase).includes('resume')&&<button className="btn-quiet" onClick={()=>tasks.current.get(job.id)?.resume()}>Resume</button>}{job.progress.phase==='failed'&&<button className="btn-quiet" onClick={()=>retry(job)}>Retry</button>}{job.progress.phase!=='complete'&&<button className="btn-quiet text-rose-600" onClick={()=>void cancel(job)}>Cancel</button>}</div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full transition-all ${job.progress.phase==='failed'?'bg-rose-500':'bg-slate-900'}`} style={{width:`${percent}%`}}/></div><div className="mt-2 flex flex-wrap justify-between gap-2 text-xs text-slate-500"><span>{percent}% · {formatBytes(job.progress.loadedBytes)} of {formatBytes(job.progress.totalBytes)}</span><span>{job.progress.speedBytesPerSecond?`${formatBytes(job.progress.speedBytesPerSecond)}/s`:job.progress.phase==='hashing'?'Computing SHA-256…':job.progress.phase==='paused'?'Waiting to resume':job.progress.phase==='completing'?'Publishing two replicas…':''}</span></div>{job.error&&<p className="mt-2 rounded-lg bg-rose-50 p-2 text-sm text-rose-700">{job.error}</p>}</div>})}</div>}
  </section>
}
