import type { FastifyInstance } from 'fastify';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { prisma } from '../../plugins/prisma.js'; import { authenticate } from '../../middleware/auth.js'; import { fileDto,folderDto } from '../../utils/dto.js'; import { fail } from '../../utils/errors.js'; import { nullableId,safeName } from '../../utils/validation.js';
const body=z.object({name:safeName,parentId:nullableId}); const rename=z.object({name:safeName}); const id=z.object({folderId:z.string().uuid()});
async function ownedFolder(folderId:string,ownerId:string){return prisma.folder.findFirst({where:{id:folderId,ownerId}})}
export async function folderRoutes(app:FastifyInstance){app.addHook('preHandler',authenticate);
 app.get('/',async(req,reply)=>{const q=z.object({parentId:z.string().uuid().nullish()}).safeParse(req.query);if(!q.success)return fail(reply,400,'VALIDATION_ERROR','Invalid parentId');const parentId=q.data.parentId??null;let current=null;if(parentId){current=await ownedFolder(parentId,req.user.sub);if(!current)return fail(reply,404,'FOLDER_NOT_FOUND','Folder not found');}const [folders,files]=await Promise.all([prisma.folder.findMany({where:{ownerId:req.user.sub,parentId},orderBy:{name:'asc'}}),prisma.file.findMany({where:{ownerId:req.user.sub,folderId:parentId},orderBy:{name:'asc'}})]);return{currentFolder:current?folderDto(current):null,folders:folders.map(folderDto),files:files.map(fileDto)}});
 app.post('/',async(req,reply)=>{const p=body.safeParse(req.body);if(!p.success)return fail(reply,400,'VALIDATION_ERROR',p.error.issues[0]?.message??'Invalid folder');const parentId=p.data.parentId??null;if(parentId&&!await ownedFolder(parentId,req.user.sub))return fail(reply,404,'FOLDER_NOT_FOUND','Folder not found');try{const f=await prisma.folder.create({data:{ownerId:req.user.sub,parentId,name:p.data.name}});return reply.code(201).send(folderDto(f));}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002')return fail(reply,409,'FOLDER_EXISTS','A folder with this name already exists');throw e;}});
 app.patch('/:folderId',async(req,reply)=>{const pi=id.safeParse(req.params),pb=rename.safeParse(req.body);if(!pi.success||!pb.success)return fail(reply,400,'VALIDATION_ERROR','Invalid request');const old=await ownedFolder(pi.data.folderId,req.user.sub);if(!old)return fail(reply,404,'FOLDER_NOT_FOUND','Folder not found');try{return folderDto(await prisma.folder.update({where:{id:old.id},data:{name:pb.data.name}}));}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002')return fail(reply,409,'FOLDER_EXISTS','A folder with this name already exists');throw e;}});
 app.delete('/:folderId',async(req,reply)=>{const p=id.safeParse(req.params);if(!p.success)return fail(reply,400,'VALIDATION_ERROR','Invalid folder id');const f=await ownedFolder(p.data.folderId,req.user.sub);if(!f)return fail(reply,404,'FOLDER_NOT_FOUND','Folder not found');const [children,files]=await Promise.all([prisma.folder.count({where:{ownerId:req.user.sub,parentId:f.id}}),prisma.file.count({where:{ownerId:req.user.sub,folderId:f.id}})]);if(children+files>0)return fail(reply,409,'FOLDER_NOT_EMPTY','Folder is not empty');await prisma.folder.delete({where:{id:f.id}});return reply.code(204).send();});
 app.get('/:folderId/breadcrumbs',async(req,reply)=>{const p=id.safeParse(req.params);if(!p.success)return fail(reply,400,'VALIDATION_ERROR','Invalid folder id');let current=await ownedFolder(p.data.folderId,req.user.sub);if(!current)return fail(reply,404,'FOLDER_NOT_FOUND','Folder not found');const result:{id:string;name:string}[]=[];while(current){result.unshift({id:current.id,name:current.name});current=current.parentId?await ownedFolder(current.parentId,req.user.sub):null;}return{breadcrumbs:result};});}
