import Fastify from 'fastify';
import cors from '@fastify/cors';
import cookie from '@fastify/cookie';
import jwt from '@fastify/jwt';
import multipart from '@fastify/multipart';
import { Prisma } from '@prisma/client';
import { ZodError } from 'zod';
import { loadEnv, parseStorageNodeEndpoints, type Env } from './config/env.js';
import { authRoutes } from './modules/auth/routes.js';
import { folderRoutes } from './modules/folders/routes.js';
import { fileRoutes } from './modules/files/routes.js';
import { userRoutes } from './modules/users/routes.js';
import { uploadRoutes } from './modules/uploads/routes.js';
import { LocalFileStorage } from './storage/local-file-storage.js';
import { AppError } from './utils/errors.js';
import { StorageNodeRegistry } from './storage/storage-node-registry.js';
import { StorageNodeHttp } from './storage/storage-node-http.js';
import { StorageMetadataService } from './modules/storage/metadata-service.js';
import { ReplicaService } from './modules/storage/replica-service.js';
import { storageRoutes } from './modules/storage/routes.js';
import { StorageOperationService } from './modules/storage/operation-service.js';
import { IntegrityService } from './modules/storage/integrity-service.js';
import { ScrubService } from './modules/storage/scrub-service.js';
import { monitoringRoutes } from './modules/monitoring/routes.js';

export async function buildApp(options:{env?:Env;logger?:boolean;storageNodes?:StorageNodeRegistry}={}){const config=options.env??loadEnv();const app=Fastify({logger:options.logger??config.NODE_ENV!=='test',bodyLimit:1_048_576});
 const storage=new LocalFileStorage(config.UPLOAD_ROOT);
 const storageNodes=options.storageNodes??new StorageNodeRegistry(parseStorageNodeEndpoints(config.STORAGE_NODE_ENDPOINTS).map(node=>new StorageNodeHttp(node.id,node.name,node.endpoint,config.STORAGE_INTERNAL_TOKEN,config.STORAGE_REQUEST_TIMEOUT_MS)));
 const storageMetadata=new StorageMetadataService(config.STORAGE_FAILURE_TIMEOUT_MS);
 const integrity=new IntegrityService(storageNodes,storage,app.log);
 const storageOperations=new StorageOperationService(storageNodes,storage,integrity,app.log);
 const scrubber=new ScrubService(integrity,storageOperations,app.log);
 app.decorate('config',config);app.decorate('storage',storage);app.decorate('storageNodes',storageNodes);app.decorate('storageMetadata',storageMetadata);app.decorate('integrity',integrity);app.decorate('storageOperations',storageOperations);app.decorate('scrubber',scrubber);app.decorate('replicas',new ReplicaService(storageNodes,storageMetadata,storageOperations,integrity,app.log));
 await app.register(cors,{origin:config.WEB_ORIGIN,credentials:true});await app.register(cookie);await app.register(jwt,{secret:config.JWT_SECRET,cookie:{cookieName:'token',signed:false}});await app.register(multipart,{limits:{files:1,fileSize:config.MAX_FILE_SIZE_BYTES,fields:4}});app.addContentTypeParser('application/octet-stream',(_req,payload,done)=>done(null,payload));
 app.setNotFoundHandler((_req,reply)=>reply.code(404).send({error:{code:'NOT_FOUND',message:'Route not found'}}));
 app.setErrorHandler((error,req,reply)=>{req.log.error(error);if(error instanceof AppError)return reply.code(error.status).send({error:{code:error.code,message:error.message}});if(error instanceof ZodError)return reply.code(400).send({error:{code:'VALIDATION_ERROR',message:'Invalid request'}});if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2025')return reply.code(404).send({error:{code:'NOT_FOUND',message:'Resource not found'}});if((error as {code?:string}).code==='FST_REQ_FILE_TOO_LARGE')return reply.code(413).send({error:{code:'FILE_TOO_LARGE',message:'File exceeds the maximum allowed size'}});return reply.code(500).send({error:{code:'INTERNAL_ERROR',message:'Internal server error'}});});
 app.get('/health',async()=>({status:'ok'}));await app.register(authRoutes,{prefix:'/api/auth'});await app.register(folderRoutes,{prefix:'/api/folders'});await app.register(fileRoutes,{prefix:'/api/files'});await app.register(uploadRoutes,{prefix:'/api/uploads'});await app.register(userRoutes,{prefix:'/api/users'});await app.register(storageRoutes,{prefix:'/api/storage'});await app.register(monitoringRoutes,{prefix:'/api/monitoring'});return app;}
