import { useState, type FormEvent, type ReactNode } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import type { BreadcrumbDto, DirectoryResponse, FileDto, StorageUsageResponse } from '@depot-drive/shared';
import { api, errorMessage } from '../api';
import { protectedQueryEnabled } from '../auth-policy';
import { useAuth } from '../auth';
import { AppShell } from '../components/AppShell';
import { StatusBadge } from '../components/StatusBadge';
import { Toast } from '../components/Toast';
import { UploadManager } from '../components/UploadManager';
import { formatBytes, formatDate } from '../format';

export function DrivePage(){
  const {folderId}=useParams(),auth=useAuth(),client=useQueryClient(),folder=folderId??null;
  const [toast,setToast]=useState(''),[newFolder,setNewFolder]=useState(false),[selected,setSelected]=useState<FileDto|null>(null);
  const enabled=protectedQueryEnabled(auth.user);
  const listing=useQuery({queryKey:['directory',folder],queryFn:async()=>(await api.get<DirectoryResponse>('/api/folders',{params:folder?{parentId:folder}:{}})).data,enabled});
  const crumbs=useQuery({queryKey:['breadcrumbs',folder],queryFn:async()=>(await api.get<{breadcrumbs:BreadcrumbDto[]}>(`/api/folders/${folder}/breadcrumbs`)).data.breadcrumbs,enabled:enabled&&!!folder});
  const usage=useQuery({queryKey:['usage'],queryFn:async()=>(await api.get<StorageUsageResponse>('/api/users/storage')).data,enabled});
  const refresh=()=>Promise.all([client.invalidateQueries({queryKey:['directory',folder]}),client.invalidateQueries({queryKey:['usage']})]);
  async function removeFile(file:FileDto){if(!confirm(`Delete “${file.name}”? This permanently removes both replicas.`))return;try{await api.delete(`/api/files/${file.id}`);setSelected(null);setToast('File deleted');await refresh()}catch(error){setToast(errorMessage(error))}}
  async function renameFile(file:FileDto){const name=prompt('Rename file',file.name)?.trim();if(!name||name===file.name)return;try{const result=await api.patch<FileDto>(`/api/files/${file.id}`,{name});setSelected(result.data);setToast('File renamed');await refresh()}catch(error){setToast(errorMessage(error))}}
  async function removeFolder(id:string,name:string){if(!confirm(`Delete empty folder “${name}”?`))return;try{await api.delete(`/api/folders/${id}`);setToast('Folder deleted');await refresh()}catch(error){setToast(errorMessage(error))}}
  const downloadUrl=(fileId:string)=>`${api.defaults.baseURL}/api/files/${fileId}/download`;
  return <AppShell title={listing.data?.currentFolder?.name??'My Drive'} description="Private files backed by two verified Storage Node replicas." actions={<><button className="btn-secondary" onClick={()=>setNewFolder(true)}>New folder</button><button className="btn-secondary" onClick={()=>void listing.refetch()}>Refresh</button></>}>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-sm"><Link className="text-slate-500 hover:text-slate-950" to="/drive">My Drive</Link>{crumbs.data?.map(item=><span className="flex items-center gap-2" key={item.id}><span className="text-slate-300">/</span><Link className="font-medium text-slate-800" to={`/drive/folder/${item.id}`}>{item.name}</Link></span>)}</nav><span className="text-sm text-slate-500">{formatBytes(usage.data?.usedBytes??0)} stored</span></div>
    <UploadManager folderId={folder} onComplete={refresh} onNotice={setToast}/>
    <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold text-slate-950">Files and folders</h2><p className="mt-0.5 text-xs text-slate-500">{(listing.data?.folders.length??0)+(listing.data?.files.length??0)} items</p></div></div>
      {listing.isLoading?<div className="space-y-3 p-5" aria-label="Loading files">{[1,2,3].map(value=><div className="skeleton h-14" key={value}/>)}</div>:listing.isError?<div className="empty-state"><p className="font-semibold text-rose-700">Could not load your drive</p><p className="mt-1 text-sm text-slate-500">{errorMessage(listing.error)}</p><button className="btn-secondary mt-4" onClick={()=>void listing.refetch()}>Try again</button></div>:!listing.data?.folders.length&&!listing.data?.files.length?<div className="empty-state"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-2xl">⌁</div><p className="mt-3 font-semibold">This folder is empty</p><p className="mt-1 text-sm text-slate-500">Upload a file or create a folder to get started.</p></div>:<div className="divide-y divide-slate-100">{listing.data?.folders.map(item=><div className="item-row" key={item.id}><Link className="flex min-w-0 flex-1 items-center gap-3" to={`/drive/folder/${item.id}`}><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-600">▰</span><div className="min-w-0"><p className="truncate font-medium text-slate-900">{item.name}</p><p className="text-xs text-slate-500">Folder · {formatDate(item.updatedAt)}</p></div></Link><button className="btn-quiet text-rose-600" onClick={()=>void removeFolder(item.id,item.name)}>Delete</button></div>)}{listing.data?.files.map(file=><div className="item-row" data-testid={`file-${file.name}`} key={file.id}><button className="flex min-w-0 flex-1 items-center gap-3 text-left" onClick={()=>setSelected(file)}><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 font-bold text-blue-600">F</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-medium text-slate-900">{file.name}</p><StatusBadge status="AVAILABLE"/></div><p className="text-xs text-slate-500 sm:hidden">{formatBytes(file.sizeBytes)} · {formatDate(file.createdAt)}</p></div><span className="hidden w-28 text-sm text-slate-500 sm:block">{formatBytes(file.sizeBytes)}</span><span className="hidden w-44 text-sm text-slate-500 lg:block">{formatDate(file.createdAt)}</span></button><a className="btn-quiet" href={downloadUrl(file.id)}>Download</a><button className="btn-quiet text-rose-600" onClick={()=>void removeFile(file)}>Delete</button></div>)}</div>}
    </section>
    {selected&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className="card w-full max-w-xl p-6" role="dialog" aria-modal="true" aria-labelledby="file-details-title"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-slate-400">File details</p><h2 id="file-details-title" className="mt-1 break-all text-xl font-bold text-slate-950">{selected.name}</h2></div><button className="btn-quiet" aria-label="Close file details" onClick={()=>setSelected(null)}>Close</button></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><Detail label="Status"><StatusBadge status="AVAILABLE"/></Detail><Detail label="Size">{formatBytes(selected.sizeBytes)}</Detail><Detail label="Uploaded">{formatDate(selected.createdAt)}</Detail><Detail label="MIME type">{selected.mimeType}</Detail><Detail label="SHA-256" wide><code className="break-all text-xs text-slate-700">{selected.checksum}</code></Detail></dl><div className="mt-6 flex flex-wrap justify-end gap-2"><button className="btn-secondary" onClick={()=>void renameFile(selected)}>Rename</button><button className="btn-secondary text-rose-600" onClick={()=>void removeFile(selected)}>Delete</button><a className="btn-primary" href={downloadUrl(selected.id)}>Download</a></div></section></div>}
    {newFolder&&<NewFolder parentId={folder} close={()=>setNewFolder(false)} saved={async()=>{setNewFolder(false);setToast('Folder created');await refresh()}}/>}<Toast message={toast} onClose={()=>setToast('')}/>
  </AppShell>
}

function Detail({label,wide,children}:{label:string;wide?:boolean;children:ReactNode}){return <div className={wide?'sm:col-span-2':''}><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 text-sm font-medium text-slate-900">{children}</dd></div>}
function NewFolder({parentId,close,saved}:{parentId:string|null;close:()=>void;saved:()=>Promise<unknown>}){const[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await api.post('/api/folders',{name,parentId});await saved()}catch(reason){setError(errorMessage(reason))}finally{setBusy(false)}}return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><form className="card w-full max-w-md p-6" onSubmit={submit}><h2 className="text-xl font-bold">Create folder</h2><label className="mt-5 block text-sm font-medium">Folder name<input autoFocus className="input mt-2" maxLength={255} required value={name} onChange={event=>setName(event.target.value)}/></label>{error&&<p className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={close}>Cancel</button><button className="btn-primary" disabled={busy||!name.trim()}>{busy?'Creating…':'Create folder'}</button></div></form></div>}
